/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-02-05 17:45:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

Connection con;
	Statement st;
	ResultSet rs;
	int no;
	String q, name1, pwd1, email1, phoneno;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');

		Class.forName("com.mysql.jdbc.Driver");
	String url = "jdbc:mysql://localhost:3307/onlinestore";
	con = DriverManager.getConnection(url, "root", "");
	st = con.createStatement();

	name1 = request.getParameter("nametxt");
	pwd1 = request.getParameter("passtxt");
	email1 = request.getParameter("emailtxt");
	phoneno = request.getParameter("phtxt");
	q = "insert into user1 values ('" + name1 + "','" + pwd1 + "','" + email1;
	q = q + "','" + phoneno + "')";
	no = st.executeUpdate(q);
	if (no > 0) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h3>");
      out.print(no);
      out.write("\r\n");
      out.write("\t\trow is inserted\r\n");
      out.write("\t</h3>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t<h3>Total Users</h3>\r\n");
      out.write("\t<table width=0>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Register number</th>\r\n");
      out.write("\t\t\t<th>password</th>\r\n");
      out.write("\t\t\t<th>email-id</th>\r\n");
      out.write("\t\t\t<th>ph_no</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			st = con.createStatement();
		rs = st.executeQuery("select * from user1");
		while (rs.next()) {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs.getString(1));
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(rs.getString(2));
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(rs.getString(3));
      out.write("\r\n");
      out.write("\t\t\t<td>");
      out.print(rs.getString(4));
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
